### ISSUE TITLE
can not find module

### ISSUE THREAD

**Issue by caxieyou** [TimvanScherpenzeel/texture-compressor#22]
I run npm install and npm install texture-compressor
then got the error as follow:
any idea?

thx

Error: Cannot find module '../dist/cli/lib/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Job\EGS\texture-compressor\bin\texture-compressor.
js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by TimvanScherpenzeel** [comment]
Hi @caxieyou, it appears that you are on Windows. It appears to be related to relative paths on Windows. I'll likely have some time next week or the week after to look into this and offer a solution, I'm unable to replicate the issue on MacOS.

**Comment by qimmer** [comment]
This seems to be related to, that the library is never built for js. The dist folder is simply missing. And when I install tsc and try to compile, I even get a lot of unsupported arguments, probably originating from tsconfig.json

**Comment by TimvanScherpenzeel** [comment]
I recently got a Windows PC so I can have a look at this soon
